// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KkxovAS_V5Nj6B2w24-r_yxCa7zHsHI',
    appId: '1:998304055211:web:f411dbc78aaa510574dcee',
    messagingSenderId: '998304055211',
    projectId: 'clarity-ba6f4',
    authDomain: 'clarity-ba6f4.firebaseapp.com',
    storageBucket: 'clarity-ba6f4.firebasestorage.app',
    measurementId: 'G-RSGTR50E99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzvZUlOyNMrxmAUfiI8ZdsSha8oxmMk_Y',
    appId: '1:998304055211:android:8faa2af74b68856c74dcee',
    messagingSenderId: '998304055211',
    projectId: 'clarity-ba6f4',
    storageBucket: 'clarity-ba6f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVo_SC2CSBjRXx5FFyZo3kOQ2W5R_Ie1c',
    appId: '1:998304055211:ios:61e7fffbe9f11b5c74dcee',
    messagingSenderId: '998304055211',
    projectId: 'clarity-ba6f4',
    storageBucket: 'clarity-ba6f4.firebasestorage.app',
    iosBundleId: 'com.example.clarityAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVo_SC2CSBjRXx5FFyZo3kOQ2W5R_Ie1c',
    appId: '1:998304055211:ios:61e7fffbe9f11b5c74dcee',
    messagingSenderId: '998304055211',
    projectId: 'clarity-ba6f4',
    storageBucket: 'clarity-ba6f4.firebasestorage.app',
    iosBundleId: 'com.example.clarityAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6KkxovAS_V5Nj6B2w24-r_yxCa7zHsHI',
    appId: '1:998304055211:web:3f916185f4f4f4c374dcee',
    messagingSenderId: '998304055211',
    projectId: 'clarity-ba6f4',
    authDomain: 'clarity-ba6f4.firebaseapp.com',
    storageBucket: 'clarity-ba6f4.firebasestorage.app',
    measurementId: 'G-VKS3151XCG',
  );
}
